# Generated by Django 5.2.17 on 2026-08-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0003_alter_salon_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salon",
            name="email",
        ),
    ]
