# Generated by Django 5.2.17 on 2026-08-17 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0004_remove_salon_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEN", "Men"),
                            ("WOMEN", "Women"),
                            ("UNISEX", "Unisex"),
                        ],
                        default="UNISEX",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "service_catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="salonservice",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salon_services",
                to="salons.servicecatalog",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonservice",
            constraint=models.UniqueConstraint(
                fields=("salon", "catalog_item"),
                name="unique_salon_catalog_item",
                nulls_distinct=True,
            ),
        ),
    ]
