# Generated by Django 5.2.17 on 2026-08-17 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0005_servicecatalog_salonservice_catalog_item_and_more"),
        ("users", "0003_salonemployee_services_alter_salonemployee_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalonFavourite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_salons",
                        to="users.customer",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "db_table": "salon_favourites",
                "unique_together": {("customer", "salon")},
            },
        ),
    ]
