# Generated by Django 5.2.17 on 2026-08-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0006_salonfavourite"),
        ("users", "0003_salonemployee_services_alter_salonemployee_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="manager",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon",
                to="users.salonmanager",
            ),
        ),
    ]
