# Generated by Django 5.2.16 on 2026-08-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('salons', '0007_alter_salon_manager_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.imagekitfile'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.imagekitfile'),
        ),
        migrations.AlterField(
            model_name='salonimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.imagekitfile'),
        ),
    ]
