# Generated by Django 5.2.16 on 2026-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_alter_salon_cover_image_alter_salon_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='salon_covers/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='salon_logos/'),
        ),
        migrations.AlterField(
            model_name='salonimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salon_gallery/'),
        ),
    ]
