# Generated by Django 5.2.16 on 2026-08-26 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageKitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagekit_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imagekit_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
