# Generated by Django 5.2.16 on 2026-08-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('salons', '0009_alter_salon_cover_image_alter_salon_logo_and_more'),
        ('users', '0005_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageKitFile',
        ),
    ]
