# Generated by Django 5.2.17 on 2026-08-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0005_servicecatalog_salonservice_catalog_item_and_more"),
        ("users", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonemployee",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="salons.salonservice"
            ),
        ),
        migrations.AlterField(
            model_name="salonemployee",
            name="position",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
