# Generated by Django 5.2.17 on 2026-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                    ("NO_SHOW", "No Show"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
